import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class Congrats extends JDialog {
    private JPanel contentPane;
    private JButton btnRes;
    private JLabel lblPic;
    private JLabel lblText;
    public JLabel lblYourTime;
    private JList<String> listRecords;
    private JLabel lblTop10;

    public Congrats(ArrayList<String[]> records, int indexRecord, JLabel lblTime) {
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(btnRes);
        setPreferredSize(new Dimension(450, 350));
        setResizable(false);
        pack();
        lblPic.setIcon(new ImageIcon((new ImageIcon(getClass().getResource("img/picDialog.JPG")))
                .getImage().getScaledInstance(200, 100, Image.SCALE_SMOOTH)));
        lblYourTime.setText("Ты справился за " + lblTime.getText());
        setLocationRelativeTo(null);
        DefaultListModel<String> dlm = new DefaultListModel<>();
        for (String[] rec : records) {// наполняем таблицу рекордов из списка
            String s = "";
            for (int i = 1; i < rec.length; i++) {
                s = s + "       " + rec[i];
            }
            dlm.addElement(s);
        }
        listRecords.setModel(dlm);
        listRecords.setSelectedIndex(indexRecord);
        listRecords.disable();
        btnRes.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {// перезапускаем игру
                Field.frame.dispose();
                new Field();
                dispose();
            }
        });
        setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 3, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        listRecords = new JList();
        listRecords.setEnabled(true);
        Font listRecordsFont = this.$$$getFont$$$("Comic Sans MS", Font.PLAIN, 12, listRecords.getFont());
        if (listRecordsFont != null) listRecords.setFont(listRecordsFont);
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        listRecords.setModel(defaultListModel1);
        panel1.add(listRecords, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 3, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        lblYourTime = new JLabel();
        Font lblYourTimeFont = this.$$$getFont$$$("Comic Sans MS", Font.PLAIN, 16, lblYourTime.getFont());
        if (lblYourTimeFont != null) lblYourTime.setFont(lblYourTimeFont);
        lblYourTime.setForeground(new Color(-10938949));
        lblYourTime.setText("Ты справился за 00:00");
        panel1.add(lblYourTime, new com.intellij.uiDesigner.core.GridConstraints(3, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRes = new JButton();
        btnRes.setText("Еще раз!");
        panel1.add(btnRes, new com.intellij.uiDesigner.core.GridConstraints(4, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblText = new JLabel();
        Font lblTextFont = this.$$$getFont$$$("Comic Sans MS", Font.PLAIN, 36, lblText.getFont());
        if (lblTextFont != null) lblText.setFont(lblTextFont);
        lblText.setForeground(new Color(-4491736));
        lblText.setText("Победа!");
        panel1.add(lblText, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblTop10 = new JLabel();
        Font lblTop10Font = this.$$$getFont$$$("Comic Sans MS", Font.PLAIN, 20, lblTop10.getFont());
        if (lblTop10Font != null) lblTop10.setFont(lblTop10Font);
        lblTop10.setForeground(new Color(-10938949));
        lblTop10.setHorizontalAlignment(0);
        lblTop10.setHorizontalTextPosition(0);
        lblTop10.setText("ТОП 10");
        panel1.add(lblTop10, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblPic = new JLabel();
        lblPic.setText("");
        panel1.add(lblPic, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }


}
